name: Fetch and Build Rota Data

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  fetch-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch rota data
      env:
        ROTA_TOKEN: ${{ secrets.ROTA_TOKEN }} # Your GitHub secret
      run: |
        # Fetch the rota data using the token
        curl -H "Authorization: $ROTA_TOKEN" https://us-central1-radrota.cloudfunctions.net/getRotaData -o rota.json

        # Ensure rota.json is included in the deployment
        mkdir -p public && mv rota.json public/

    - name: Build site (if necessary)
      run: npm run build # Adjust for your project or skip if unnecessary

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
