name: Fetch and Build Rota Data

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  fetch-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch rota data
      env:
        ROTA_TOKEN: ${{ secrets.ROTA_TOKEN }} # Access the secret securely
      run: |
        # Use the token to fetch data from the API
        curl -H "Authorization: $ROTA_TOKEN" https://us-central1-radrota.cloudfunctions.net/getRotaData -o rota.json

        # Move rota.json to the public directory (or your deployment directory)
        mkdir -p public && mv rota.json public/

    - name: Build static site (optional)
      run: npm run build # Adjust this for your static site generator or skip if unnecessary

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
